Tarea6/Models/Domain/Employee.cs
namespace Tarea6.Models.Domain
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        public string Email { get; set; }

        public long Salary { get; set; }

        public DateTime DateOfBirth { get; set; }

        public string Departament { get; set; }


    }
}

Tarea6/Models/ViewModels/AddEmployeeViewModel.cs
namespace Tarea6.Models.ViewModels
{
	public class AddEmployeeViewModel
	{

		public string Name { get; set; }

		public string Email { get; set; }

		public long Salary { get; set; }

		public DateTime DateOfBirth { get; set; }

		public string Departament { get; set; }
	}
}

Tarea6/Models/ViewModels/EditEmployeeViewModel.cs
namespace Tarea6.Models.ViewModels
{
	public class EditEmployeeViewModel
	{
		public Guid Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }
		public long Salary { get; set; }
		public DateTime DateOfBirth { get; set; }
		public string Departament { get; set; }
	}
}

Tarea6/Pages/Employees/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tarea6.Data;
using Tarea6.Models.Domain;
using Tarea6.Models.ViewModels;

namespace Tarea6.Pages.Employees
{
    public class AddModel : PageModel
    {
		private readonly RazorPagesDemoDbContext dbContext;

		public AddModel(RazorPagesDemoDbContext dbContext)
        {
			this.dbContext = dbContext;
		}
        [BindProperty]
        public AddEmployeeViewModel AddEmployeeRequest { get; set; }

        public void OnGet()
        {
        }

        public void OnPost()
        {
            //Convierto el ViewModel a DomainModel
            var empleyeeDomainModel = new Employee
            {
                Name = AddEmployeeRequest.Name,
                Email = AddEmployeeRequest.Email,
                Salary = AddEmployeeRequest.Salary,
                DateOfBirth = AddEmployeeRequest.DateOfBirth,
                Departament = AddEmployeeRequest.Departament
            };
            dbContext.Employees.Add(empleyeeDomainModel);
            dbContext.SaveChanges();

            ViewData["Message"] = "Empleado creado";
        }
    }
}

Tarea6/Pages/Employees/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tarea6.Data;
using Tarea6.Models.ViewModels;

namespace Tarea6.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;
        [BindProperty]

        public EditEmployeeViewModel EditEmployeeViewModel { get; set; }

        public EditModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet(Guid id)
        {
            var employee = dbContext.Employees.Find(id);
            if (employee != null)
            {
                EditEmployeeViewModel = new EditEmployeeViewModel()
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    Email = employee.Email,
                    DateOfBirth = employee.DateOfBirth,
                    Salary = employee.Salary,
                    Departament = employee.Departament
                };
            }
        }

        public void OnPostUpdate()
        {
            if (EditEmployeeViewModel != null)
            {
                var existingEmployee = dbContext.Employees.Find(EditEmployeeViewModel.Id);
                if (existingEmployee != null)
                {

                    existingEmployee.Name = EditEmployeeViewModel.Name;
                    existingEmployee.Email = EditEmployeeViewModel.Email;
                    existingEmployee.Salary = EditEmployeeViewModel.Salary;
                    existingEmployee.DateOfBirth = EditEmployeeViewModel.DateOfBirth;
                    existingEmployee.Departament = EditEmployeeViewModel.Departament;

                    dbContext.SaveChanges();
                    ViewData["Message"] = "Empleado ha sido Modificado";

                }
            }
        }
        public IActionResult OnPostDelete()
        {
			var existingEmployee = dbContext.Employees.Find(EditEmployeeViewModel.Id);
            if(existingEmployee != null)
            {
                dbContext.Employees.Remove(existingEmployee);
                dbContext.SaveChanges();

                return RedirectToPage("/Employees/List");

            }
            return Page();

		}
	}
}

Tarea6/Pages/Employees/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tarea6.Data;

namespace Tarea6.Pages.Employees
{
    public class ListModel : PageModel
    {
		private readonly RazorPagesDemoDbContext dbContext;
        public List<Models.Domain.Employee> Employees { get; set; }


		public ListModel(RazorPagesDemoDbContext dbContext) 
        {
			this.dbContext = dbContext;
		}
        public void OnGet()
        {

			Employees = dbContext.Employees.ToList();
        }
    }
}

Tarea6/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Tarea6.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Tarea6/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tarea6.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Tarea6/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tarea6.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Tarea6/Pages/Employees/Add.cshtml
@page
@model Tarea6.Pages.Employees.AddModel
@{
	var message = ViewData["Message"]?.ToString();

}

<form method="post">
	<h1 class="mb-3">Añadir Nuevo Empleado</h1>

	@if (!string.IsNullOrWhiteSpace(message))
	{
		<div class="alert alert-success" role="alert">
			@message
		</div>
	}

	<div class="mb-3">
		<label>Nombre del Empleado</label>
		<input type="text" class="form-control" asp-for="AddEmployeeRequest.Name"/>
	</div>

	<div class="mb-3">
		<label>Email</label>
		<input type="email" class="form-control" asp-for="AddEmployeeRequest.Email"/>
	</div>

	<div class="mb-3">
		<label>Salario</label>
		<input type="number" class="form-control" asp-for="AddEmployeeRequest.Salary"/>
	</div>

	<div class="mb-3">
		<label>Fecha de Nacimiento</label>
		<input type="date" class="form-control" asp-for="AddEmployeeRequest.DateOfBirth"/>
	</div>

	<div class="mb-3">
		<label>Departamento</label>
		<input type="text" class="form-control" asp-for="AddEmployeeRequest.Departament"/>
	</div>

	<div class="mb-3 d-flex justify-content-between"">
		<button type="submit" class="btn btn-primary">Guardar</button>
		<a href="/Employees/List" class="btn btn-success">Regresar</a>

	</div>

</form>

Tarea6/Pages/Employees/Edit.cshtml
@page "{id:Guid}"
@model Tarea6.Pages.Employees.EditModel
@{
}
@{
	var message = ViewData["Message"]?.ToString();
}

<form method="post">
	<h1 class="mb-3">Editar Empleado</h1>


	@if (!string.IsNullOrWhiteSpace(message))
	{
			<div class="alert alert-success" role="alert">
			@message
			</div>
	}


	<div class="mb-3">
		<label class="form-label">Id</label>
		<input type="text" class="form-control" asp-for="EditEmployeeViewModel.Id" readonly />		
	</div>

	<div class="mb-3">
		<label class="form-label">Nombre</label>
		<input type="text" class="form-control" asp-for="EditEmployeeViewModel.Name"  />		
	</div>

	<div class="mb-3">
		<label class="form-label">Email</label>
		<input type="email" class="form-control" asp-for="EditEmployeeViewModel.Email"  />		
	</div>

	<div class="mb-3">
		<label class="form-label">Salario</label>
		<input type="number" class="form-control" asp-for="EditEmployeeViewModel.Salary"  />		
	</div>

	<div class="mb-3">
		<label class="form-label">Fecha de Nacimiento</label>
		<input type="date" class="form-control" asp-for="EditEmployeeViewModel.DateOfBirth"  />		
	</div>

	<div class="mb-3">
		<label class="form-label">Departamento</label>
		<input type="text" class="form-control" asp-for="EditEmployeeViewModel.Departament"  />		
	</div>

	<div class="mb-3 d-flex justify-content-between">
		<button type="submit" class="btn btn-primary" asp-page-handler="Update">
			Actualizar
		</button>

		<button type="submit" class="btn btn-danger" asp-page-handler="Delete">
			Eliminar
		</button>
		
		<a href="/Employees/List" class="btn btn-success">Regresar</a>
	</div>


</form>

Tarea6/Pages/Employees/List.cshtml
@page
@model Tarea6.Pages.Employees.ListModel
@{
}

<h1 class="mb-3">Lista de Empleados</h1>
<a href="/Employees/Add" class="btn btn-success">Añadir Empleado</a>
@if (Model.Employees != null && Model.Employees.Any())
{
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nombre</th>
				<th>Email</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var employee in Model.Employees)
			{
				<tr>
					<td>@employee.Id</td>
					<td>@employee.Name</td>
					<td>@employee.Email</td>
					<td>@employee.Departament</td>
					<td>
						<a href="/Employees/Edit/@employee.Id" class="btn btn-dark">Editar</a>
					</td>
				</tr>
				
			}

		</tbody>
	</table>
	
}
else
{
	<p>No existen Empleados</p>
}

Tarea6/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

	<div class="col-md-6 col-md-offset-3 text-center wrap_title">
		<h2>Gestión de Empleados</h2>
		<p class="lead" style="margin-top:0">Herramientas y otros recursos ocupados.</p>

	</div>
	<div id="whatis" class="content-section-b" style="border-top: 0">
		<div class="container">
			<div class="row">

				<div class="col-sm-4 wow fadeInDown text-center">
				  <img class="rotate" src="img/icon/browser.svg" alt="Generic placeholder image">
				  <h3>Lenguaje C#</h3>

				</div>

				<div class="col-sm-4 wow fadeInDown text-center">
				  <img  class="rotate" src="img/icon/picture.svg" alt="Generic placeholder image">
				   <h3>Data Base SQL</h3>

				</div>

				<div class="col-sm-4 wow fadeInDown text-center">
				  <img  class="rotate" src="img/icon/retina.svg" alt="Generic placeholder image">
				   <h3>CSS</h3>
				</div>

			</div>

			<div class="row tworow">

				<div class="col-sm-4  wow fadeInDown text-center">
				  <img class="rotate" src="img/icon/laptop.svg" alt="Generic placeholder image">
				  <h3>Responsive</h3>

				</div>

				<div class="col-sm-4 wow fadeInDown text-center">
				  <img  class="rotate" src="img/icon/map.svg" alt="Generic placeholder image">
				   <h3>Google</h3>
				</div>

				<div class="col-sm-4 wow fadeInDown text-center">
				  <img  class="rotate" src="img/icon/browser.svg" alt="Generic placeholder image">
				   <h3>Bootstrap</h3>

				</div>

			</div>
		</div>
	</div>

Tarea6/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tarea6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tarea6.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css1/general.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css1/style.css" asp-append-version="true" />


    
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
    
    <script src="~js1/modernizr-2.8.3.min.js"></script>  

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/Employees/List">Lista de Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Tarea6 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>